### ISSUE TITLE
Landing page images not rendering on firefox and safari

### ISSUE THREAD

**Issue by TdhyunK** [alexdanilowicz/client-leftonread#13]

**Comment by TdhyunK** [comment]
Turns out this bug isn't on our end but more of a firefox/safari bug. Here's the github issue for it: https://github.com/webpack-contrib/style-loader/issues/303

Apparently firefox has a bug when working with `style-loader` which is basically a css loader that we use in our webpack config. I fixed this bug by just putting absolute paths to the images rather than making them `import message from 'apple-messages.png'.

**Comment by alexdanilowicz** [comment]
And this broke travis, right? So this card is in limbo?
